spring:
  application:
    name: entree-service

server:
  port: 8081

#eureka:
#  instance:
#     preferIpAddress: true
#  client:
#    serviceUrl:
#       defaultZone: TBD

wfd:
  entree:
    order: 2
    type: dinner
    menu:
      - Steak
      - Chicken
      - Fish
